import Head from "next/head";
import HodlRecConts from "../components/HodlRecConts";
import Welcome from "../components/Welcome";
import Navbar from "../components/NavBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>HodlBank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome />
      <div className="px-3">
        <HodlRecConts />
      </div>
    </div>
  );
}
